# Generated by Django 3.1.6 on 2022-04-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conciertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('nombrecorto', models.CharField(max_length=30)),
                ('fecha_grabacion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='')),
                ('imagen_thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField()),
            ],
            options={
                'db_table': 'conciertos',
                'managed': False,
            },
        ),
    ]
